### ISSUE TITLE
Missing privacy policy

### ISSUE THREAD

**Issue by NicolasCARPi** [JoachimGoedhart/PlotsOfData#10]
Hello,

What happens to the data I might upload on the website? I couldn't find any privacy policy about it.

How long is it stored, who has access to it, can I request deletion, things like that.

**Comment by JoachimGoedhart** [comment]
Thanks for raising this issue. There is no explicit instruction in the app.R code to store the data. Still, it is possible that user data is temporarily stored on the shiny server. However, it is beyond my expertise to tell you whether this is the case.
If you want to be absolutely sure that your data cannot be accessed and is not stored on the server you can run it locally (i.e. running the app from R or Rstudio).
Finally, we do have no interest in your data. We are interested in the graphs that users make and we would be very happy if those are shared (e.g. on twitter mentioning #PlotsOfData).

**Comment by NicolasCARPi** [comment]
Cheers :)
