### ISSUE TITLE
Can't plot data

### ISSUE THREAD

**Issue by hg16307** [JoachimGoedhart/PlotsOfData#12]
Hi, 
I am trying to do a violin plot for my data, but it keeps saying 'Error: An error has occurred'.
I have used the same dataset to plot violin plot lots in the last few days, so I don't think I'm inputting it wrong. 
Is this a known error here, or am I making a mistake?
Thanks

**Comment by JoachimGoedhart** [comment]
Thanks for the notification. I'm not sure what's going on, the app has not been changed recently. It seems to run OK from Rstudio/Github, so you can use this in the meantime as a workaround. In R/Rstudio type:
shiny::runGitHub('PlotsOfData', 'JoachimGoedhart')

Another alternative is to use PlotsOfDifferences, which works OK. You can disable the display of the effect size if you want:
https://huygens.science.uva.nl/PlotsOfDifferences/

I will look into this issue and try to fix it....

**Comment by hg16307** [comment]
Thanks very much!
It works fine on this new link.
I appreciate the quick response (as my dissertation is due at the end of the week!)

**Comment by JoachimGoedhart** [comment]
Good luck with the dissertation! Let me know if any other issues arise…

Best Regards,
Joachim.


> On May 1, 2019, at 15:07 , hg16307 <notifications@github.com> wrote:
> 
> Thanks very much!
> It works fine on this new link.
> I appreciate the quick response (as my dissertation is due at the end of the week!)
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

__________________________________________

Dr. Joachim Goedhart
Assistant Professor
Section Molecular Cytology
SILS | University of Amsterdam

Web: http://www.molcyto.nl/Joachim/
Twitter: @joachimgoedhart
Tel: +31(0)20 525 7774
__________________________________________

**Comment by R180** [comment]
I believe there's a problem with the web app. It works for wide format (Example 1) data, but the Example 2 data (tidy format) generates the error.
<img width="643" alt="zzz666" src="https://user-images.githubusercontent.com/16230091/72696938-0b182700-3b0c-11ea-9f74-ba0c3eccbb84.png">

**Comment by JoachimGoedhart** [comment]
Thanks for the comment - can you send me the data, so I can check what's going on?
You may send it to:
 j #dot# goedhart #at# uva #dot# nl

**Comment by R180** [comment]
Hi. I don't have the data. It's the example data, "Example 2 (tidy
format)", that you've built into the app.

**Comment by JoachimGoedhart** [comment]
Ah, ok. After selecting 'Example 2', you can active the checkbox "These data are tidy" and after that you can select the data to plot. Does that work?

**Comment by R180** [comment]
OK. That fixed it.

**Comment by JoachimGoedhart** [comment]
Fixed
