### ISSUE TITLE
server down?

### ISSUE THREAD

**Issue by rica01** [JoachimGoedhart/PlotsOfData#15]
Hello! Love the shinyapp but it seems your server went down?

I cannot access it since last friday. https://huygens.science.uva.nl/PlotsOfData/

**Comment by JoachimGoedhart** [comment]
Thanks for the note - I'll look into it. In the meantime these alternatives can be used:
https://huygens.science.uva.nl/PlotsOfData2/
http://amsterdamstudygroup.shinyapps.io/PlotsOfData/
