### ISSUE TITLE
An error has occurred. Check your logs or contact the app author for clarification

### ISSUE THREAD

**Issue by danknight** [JoachimGoedhart/PlotsOfData#2]
Hi, I love this app, Please can you advise how I can get the attached data set to work? I'm clearly doing something wrong as I
[Book1.xlsx](https://github.com/JoachimGoedhart/PlotsOfData/files/2463856/Book1.xlsx)
 keep getting the error message: _An error has occurred. Check your logs or contact the app author for clarification._

The demo datasets work fine.
Sorry if its something really obvious

Cheers
Dan

**Comment by JoachimGoedhart** [comment]
Hi Dan,

Thanks for the comment. Looks like the (bp) causes a problem. A quick fix is to remove this from the excel file, here's the file with modified header that works for me: 
[Book1.xlsx](https://github.com/JoachimGoedhart/PlotsOfData/files/2557538/Book1.xlsx)

Hope this helps,
Joachim.

**Comment by danknight** [comment]
Thanks so much Joachim!
