### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by pawelthebiologist** [JoachimGoedhart/PlotsOfData#9]
I am unable to run the app. I am getting the following error messages:

Listening on http://127.0.0.1:4085
Warning: Error in renderDataTable: unused arguments (rownames = FALSE, editable = FALSE, selection = "none")
  50: server [#422]
Error in renderDataTable(df_filtered(), rownames = FALSE, options = list(pageLength = 100,  : 
  unused arguments (rownames = FALSE, editable = FALSE, selection = "none")
Warning: Error in df_summary_mean: could not find function "df_summary_mean"
  [No stack trace available]
Warning: Error in df_summary_mean: could not find function "df_summary_mean"
  [No stack trace available]
Warning: Error in renderDataTable: unused arguments (rownames = FALSE, editable = FALSE, selection = "none")
  50: server [#422]
Error in renderDataTable(df_filtered(), rownames = FALSE, options = list(pageLength = 100,  : 
  unused arguments (rownames = FALSE, editable = FALSE, selection = "none")
Warning: Error in df_summary_mean: could not find function "df_summary_mean"
  [No stack trace available]
Warning: Error in df_summary_mean: could not find function "df_summary_mean"
  [No stack trace available]

I tried running the app from github using shiny::runGitHub, as well as locally 
R version 3.5.1, RStudio version 1.0.143

**Comment by JoachimGoedhart** [comment]
If you run from GitHub (in RStudio) using
>shiny::runGitHub('PlotsOfData', 'JoachimGoedhart')

can you see in the command line whether all packages are attached/loaded?
(I'm using RStudio Version 1.1.453, R version 3.3.3)
